version: "3.10"

services:
  arlina-api:
    hostname: arlina-api
    container_name: arlina-api
    image: arlinadocker/api:${IMAGE_VERSION}-native
    restart: unless-stopped
    environment:
      - QUARKUS_HTTP_CORS_ORIGINS=${CORS_ORIGINS}
      - QUARKUS_DATASOURCE_USERNAME=${MYSQL_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - MP_JWT_VERIFY_PUBLICKEY_LOCATION=/jwt/publicKey.pem
      - QUARKUS_MINIO_ARLINA_URL=http://arlina-minio:9000/
      - QUARKUS_MINIO_ARLINA_ACCESS_KEY=${MINIO_ARLINA_ACCESS_KEY}
      - QUARKUS_MINIO_ARLINA_SECRET_KEY=${MINIO_ARLINA_SECRET_KEY}
      - QUARKUS_CONTAINER_IMAGE_TAG=${IMAGE_VERSION}
    ports:
      - "${API_PORT}:${API_PORT}"
    expose:
      - ${API_PORT}
    volumes:
      - ./jwt:/jwt
    networks:
      - arlinamp

  arlina-jwt:
    hostname: arlina-jwt
    container_name: arlina-jwt
    image: arlinadocker/auth-jwt:${IMAGE_VERSION}-native
    restart: unless-stopped
    environment:
      - QUARKUS_HTTP_CORS_ORIGINS=${CORS_ORIGINS}
      - QUARKUS_DATASOURCE_USERNAME=${MYSQL_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - SMALLRYE_JWT_SIGN_KEY_LOCATION=/jwt/privateKey.pem
      - MP_JWT_VERIFY_PUBLICKEY_LOCATION=/jwt/publicKey.pem
      - DATA_COMPANY_EMAIL=${DATA_COMPANY_EMAIL}
      - DATA_DUMMY_PASSWORD=${DATA_DUMMY_PASSWORD}
      - QUARKUS_CONTAINER_IMAGE_TAG=${IMAGE_VERSION}
    ports:
      - "${JWT_PORT}:${JWT_PORT}"
    expose:
      - ${JWT_PORT}
    volumes:
      - ./jwt:/jwt
    networks:
      - arlinamp

  arlina-admin:
    container_name: arlina-admin
    hostname: arlina-admin
    image: arlinadocker/arlina-admin:${IMAGE_VERSION}
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - ${REACT_APP_WEB_ADMIN_PORT}:80
    expose:
      - ${REACT_APP_WEB_ADMIN_PORT}

  arlina-user:
    container_name: arlina-user
    hostname: arlina-user
    image: arlinadocker/arlina-user:${IMAGE_VERSION}
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - ${REACT_APP_WEB_USER_PORT}:80
    expose:
      - ${REACT_APP_WEB_USER_PORT}

  arlina-minio:
    hostname: arlina-minio
    container_name: arlina-minio
    image: quay.io/minio/minio:RELEASE.2023-07-07T07-13-57Z
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKETS}
    ports:
      - "${MINIO_PORTAL_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    expose:
      - "${MINIO_PORTAL_PORT}"
      - "${MINIO_CONSOLE_PORT}"
    volumes:
      - minio-data:/data
      - ./minio:/scripts
    command: server /data --console-address ':9001'
    networks:
      - arlinamp

volumes:
  minio-data:

networks:
  arlinamp:
    driver: bridge
